version: '3.7'

services:
  db:
    image: postgres:13.13-alpine
    container_name: fiap-desafio-db    
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - fiap-desafio-db-data:/var/lib/postgresql/data
    networks:
      - default
    
  app:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: fiap-desafio-app
    restart: always
    env_file:
      - .env
    ports:
      - ${APP_PORT:-3000}:3000
    depends_on:
      - db
    networks:
      - default

volumes:
  fiap-desafio-db-data:

networks:
  default:
    name: fiap-desafio-network
