version: '3.7'

services:
  db:
    image: postgres:13.13-alpine
    container_name: fiap-desafio-db    
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-fiap-desafio-db}
    ports:
      - ${POSTGRES_PORT:-5432}:5432

networks:
  default:
    name: fiap-desafio-network
